name: flutter_paystack
description: A Flutter plugin for making payments via Paystack Payment Gateway. Completely supports Android and iOS.
version: 1.0.4+1
author: Wilberforce Uwadiegwu <faradaywilly@gmail.com>
homepage: https://github.com/wilburt/flutter_paystack

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  intl: ^0.17.0
  meta: ^1.3.0
  async: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: ^0.12.10
  mockito: ^4.1.4


flutter:
  plugin:
    platforms:
      android:
        package: co.paystack.flutterpaystack
        pluginClass: FlutterPaystackPlugin
      ios:
        pluginClass: FlutterPaystackPlugin

  assets:
    - assets/images/

